default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: letsapp 
  password: <%= ENV['LETSAPP_DATABASE_PASSWORD'] %>

#  host: 35.247.173.139
  host: 127.0.0.1

development:
  <<: *default
  #database: jumpstart_development
  database: fc4

test:
  <<: *default
  database: fc4

production:
  <<: *default
  database: fc4
